### PR TITLE
Add bootstrap-3 material theme for crispy forms

### PR DESCRIPTION
**Pull request by jem2305**

### CODE REVIEW

**Review by jem2305 — COMMENTED** [review]
All *.html files were copied from the THINK repo

**Review by mwm5945 — COMMENTED** [review]
does the time picker work?

**Review by mwm5945 — APPROVED** [review]

**Comment by jem2305** [comment]
Haven't tested, not sure if its an additional plugin or not. Those class additions are pulled directly from THINK.

**Comment by mwm5945** [comment]
Just tried, it doesn't work--on the next merge take out the CRISPY_CLASS_CONVERTERS line in the settings file--nbd

**Pull request merged**
